# Generated by Django 6.1 on 2026-08-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_id', models.AutoField(db_column='pago_id', primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(db_column='metodo_pago', max_length=50)),
                ('monto_pagado', models.DecimalField(db_column='monto_pagado', decimal_places=2, max_digits=10)),
                ('comision_plataforma', models.DecimalField(db_column='comision_plataforma', decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(db_column='estado_pago', max_length=50)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, db_column='fecha_pago')),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reservas.reservaspedidos')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
