# Generated by Django 6.1 on 2026-08-14 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoria_id', models.AutoField(db_column='categoria_id', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='nombre_categoria', max_length=100)),
                ('descripcion', models.TextField(db_column='descripcion', default='')),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='PerfilesFotografos',
            fields=[
                ('perfil_id', models.AutoField(db_column='perfil_id', primary_key=True, serialize=False)),
                ('biografia', models.TextField(blank=True, db_column='biografia', default='')),
                ('especialidad', models.CharField(db_column='especialidad', max_length=100)),
                ('tarifa_base', models.DecimalField(db_column='tarifa_base', decimal_places=2, max_digits=10)),
                ('enlace_portafolio', models.CharField(blank=True, db_column='enlace_portafolio', default='', max_length=255)),
            ],
            options={
                'db_table': 'perfiles_fotografos',
            },
        ),
        migrations.CreateModel(
            name='ReservasPedidos',
            fields=[
                ('pedido_id', models.AutoField(db_column='pedido_id', primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, db_column='fecha_pedido')),
                ('fecha_sesion_reservada', models.DateTimeField(db_column='fecha_sesion_reservada')),
                ('estado_pedido', models.CharField(db_column='estado_pedido', max_length=50)),
                ('total_pedido', models.DecimalField(db_column='total_pedido', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'reservas_pedidos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rol_id', models.AutoField(db_column='rol_id', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='nombre_rol', max_length=50)),
                ('descripcion', models.TextField(db_column='descripcion', default='')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='ServiciosProductos',
            fields=[
                ('item_id', models.AutoField(db_column='item_id', primary_key=True, serialize=False)),
                ('nombre_item', models.CharField(db_column='nombre_item', max_length=150)),
                ('descripcion', models.TextField(db_column='descripcion', default='')),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=10)),
                ('tipo_item', models.CharField(choices=[('Digital', 'Digital'), ('Impresión', 'Impresión'), ('Sesión', 'Sesión')], db_column='tipo_item', max_length=20)),
                ('stock', models.IntegerField(db_column='stock', default=0)),
            ],
            options={
                'db_table': 'servicios_productos',
            },
        ),
        migrations.CreateModel(
            name='PortafoliosGalerias',
            fields=[
                ('galeria_id', models.AutoField(db_column='galeria_id', primary_key=True, serialize=False)),
                ('titulo_obra', models.CharField(db_column='titulo_obra', max_length=150)),
                ('descripcion', models.TextField(db_column='descripcion', default='')),
                ('imagen_url', models.CharField(db_column='imagen_url', max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_column='fecha_subida')),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, related_name='galerias', to='marketplace.categorias')),
                ('fotografo', models.ForeignKey(db_column='fotografo_id', on_delete=django.db.models.deletion.CASCADE, related_name='galerias', to='marketplace.perfilesfotografos')),
            ],
            options={
                'db_table': 'portafolios_galerias',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_id', models.AutoField(db_column='pago_id', primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(db_column='metodo_pago', max_length=50)),
                ('monto_pagado', models.DecimalField(db_column='monto_pagado', decimal_places=2, max_digits=10)),
                ('comision_plataforma', models.DecimalField(db_column='comision_plataforma', decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(db_column='estado_pago', max_length=50)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, db_column='fecha_pago')),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='marketplace.reservaspedidos')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.AddField(
            model_name='reservaspedidos',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='marketplace.serviciosproductos'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(db_column='usuario_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellido', models.CharField(db_column='apellido', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=150, unique=True)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255)),
                ('telefono', models.CharField(blank=True, db_column='telefono', default='', max_length=20)),
                ('direccion', models.TextField(blank=True, db_column='direccion', default='')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='marketplace.roles')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='serviciosproductos',
            name='fotografo',
            field=models.ForeignKey(db_column='fotografo_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='marketplace.usuarios'),
        ),
        migrations.CreateModel(
            name='Reseñas',
            fields=[
                ('reseña_id', models.AutoField(db_column='reseña_id', primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(db_column='calificacion')),
                ('comentario', models.TextField(db_column='comentario', default='')),
                ('fecha_reseña', models.DateTimeField(auto_now_add=True, db_column='fecha_reseña')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_emitidas', to='marketplace.usuarios')),
                ('fotografo', models.ForeignKey(db_column='fotografo_id', on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_recibidas', to='marketplace.usuarios')),
            ],
            options={
                'db_table': 'reseñas',
            },
        ),
        migrations.AddField(
            model_name='reservaspedidos',
            name='cliente',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to='marketplace.usuarios'),
        ),
        migrations.AddField(
            model_name='reservaspedidos',
            name='fotografo',
            field=models.ForeignKey(db_column='fotografo_id', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_fotografo', to='marketplace.usuarios'),
        ),
        migrations.AddField(
            model_name='perfilesfotografos',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='marketplace.usuarios'),
        ),
    ]
