# Generated by Django 6.1 on 2026-08-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortafoliosGalerias',
            fields=[
                ('galeria_id', models.AutoField(db_column='galeria_id', primary_key=True, serialize=False)),
                ('titulo_obra', models.CharField(db_column='titulo_obra', max_length=150)),
                ('descripcion', models.TextField(db_column='descripcion', default='')),
                ('imagen_url', models.CharField(db_column='imagen_url', max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_column='fecha_subida')),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, related_name='galerias', to='categorias.categorias')),
                ('fotografo', models.ForeignKey(db_column='fotografo_id', on_delete=django.db.models.deletion.CASCADE, related_name='galerias', to='perfiles.perfilesfotografos')),
            ],
            options={
                'db_table': 'portafolios_galerias',
            },
        ),
    ]
