# Generated by Django 6.1 on 2026-08-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosProductos',
            fields=[
                ('item_id', models.AutoField(db_column='item_id', primary_key=True, serialize=False)),
                ('nombre_item', models.CharField(db_column='nombre_item', max_length=150)),
                ('descripcion', models.TextField(db_column='descripcion', default='')),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=10)),
                ('tipo_item', models.CharField(choices=[('Digital', 'Digital'), ('Impresión', 'Impresión'), ('Sesión', 'Sesión')], db_column='tipo_item', max_length=20)),
                ('stock', models.IntegerField(db_column='stock', default=0)),
                ('fotografo', models.ForeignKey(db_column='fotografo_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'servicios_productos',
            },
        ),
    ]
