# Generated by Django 6.1 on 2026-08-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilesFotografos',
            fields=[
                ('perfil_id', models.AutoField(db_column='perfil_id', primary_key=True, serialize=False)),
                ('biografia', models.TextField(blank=True, db_column='biografia', default='')),
                ('especialidad', models.CharField(db_column='especialidad', max_length=100)),
                ('tarifa_base', models.DecimalField(db_column='tarifa_base', decimal_places=2, max_digits=10)),
                ('enlace_portafolio', models.CharField(blank=True, db_column='enlace_portafolio', default='', max_length=255)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'perfiles_fotografos',
            },
        ),
    ]
