# Generated by Django 6.1 on 2026-08-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(db_column='usuario_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellido', models.CharField(db_column='apellido', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=150, unique=True)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255)),
                ('telefono', models.CharField(blank=True, db_column='telefono', default='', max_length=20)),
                ('direccion', models.TextField(blank=True, db_column='direccion', default='')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='roles.roles')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
