# Generated by Django 6.1 on 2026-08-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoria_id', models.AutoField(db_column='categoria_id', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='nombre_categoria', max_length=100)),
                ('descripcion', models.TextField(db_column='descripcion', default='')),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
    ]
