# Generated by Django 6.1 on 2026-08-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rol_id', models.AutoField(db_column='rol_id', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='nombre_rol', max_length=50)),
                ('descripcion', models.TextField(db_column='descripcion', default='')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
