# Generated by Django 6.1 on 2026-08-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseñas',
            fields=[
                ('reseña_id', models.AutoField(db_column='reseña_id', primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(db_column='calificacion')),
                ('comentario', models.TextField(db_column='comentario', default='')),
                ('fecha_reseña', models.DateTimeField(auto_now_add=True, db_column='fecha_reseña')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_emitidas', to='usuarios.usuarios')),
                ('fotografo', models.ForeignKey(db_column='fotografo_id', on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_recibidas', to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'reseñas',
            },
        ),
    ]
