# Generated by Django 6.1 on 2026-08-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservasPedidos',
            fields=[
                ('pedido_id', models.AutoField(db_column='pedido_id', primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, db_column='fecha_pedido')),
                ('fecha_sesion_reservada', models.DateTimeField(db_column='fecha_sesion_reservada')),
                ('estado_pedido', models.CharField(db_column='estado_pedido', max_length=50)),
                ('total_pedido', models.DecimalField(db_column='total_pedido', decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to='usuarios.usuarios')),
                ('fotografo', models.ForeignKey(db_column='fotografo_id', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_fotografo', to='usuarios.usuarios')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='servicios.serviciosproductos')),
            ],
            options={
                'db_table': 'reservas_pedidos',
            },
        ),
    ]
